# Generated by Django 5.1.4 on 2025-01-01 17:47

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=localflavor.br.models.BRCPFField(
                blank=True, max_length=14, null=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="cpf",
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name="CPF"),
        ),
    ]
